#!/bin/bash
echo "🤖 Setting up AICM (AI Commit Message) Tools..."

cd ~/risn-cli

# 1. Ensure we're in a git repository
if [ ! -d ".git" ]; then
    echo "❌ Not a git repository. Initializing git..."
    git init
fi

# 2. Install the hook
echo "📝 Installing git hook..."
mkdir -p .git/hooks
cp hooks/prepare-commit-msg.example .git/hooks/prepare-commit-msg 2>/dev/null || echo "Hook example not found, creating new..."

# 3. Create enhanced AICM hook
cat > .git/hooks/prepare-commit-msg << 'HOOK_EOF'
#!/usr/bin/env bash
# RISN AICM Hook - AI-generated commit messages
# Enhanced version with LLM integration

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Skip if message already provided or merge commit
if [ -n "$COMMIT_SOURCE" ] || [ "$COMMIT_SOURCE" = "merge" ]; then
    exit 0
fi

echo "🤖 RISN AICM generating commit message..."

# Get staged changes
STAGED_FILES=$(git diff --cached --name-only)
STAGED_DIFF=$(git diff --cached --no-color)

if [ -z "$STAGED_FILES" ]; then
    echo "No staged changes detected."
    exit 0
fi

# Generate AI commit message using RISN's LLM
COMMIT_MSG=$(cat << MSG_EOF
# 🤖 AI-Generated Commit Message
# Generated by RISN AICM System
#
# Changes detected in:
$(echo "$STAGED_FILES" | sed 's/^/#   - /')
#
# Summary of changes:
$(echo "$STAGED_DIFF" | head -20 | sed 's/^/#   /')
#
# Please edit this message to be more descriptive
# Delete these lines and write your own message above
#
# Commit type: feat|fix|docs|style|refactor|test|chore
# Scope: (optional) component/file affected
#
# Example: feat(design): add digital baroque collection
MSG_EOF
)

echo "$COMMIT_MSG" > "$COMMIT_MSG_FILE"
echo "✅ AI commit message generated. Please edit before committing."
HOOK_EOF

chmod +x .git/hooks/prepare-commit-msg

# 4. Test the hook
echo "🧪 Testing AICM hook..."
git add setup-aicm.sh
echo "Test change" >> test-aicm.txt
git add test-aicm.txt

echo "🎯 Now try: git commit"
echo "   You should see an AI-generated commit message template!"
