/**
 * risn aicm commit [--hook install]
 * Produces Conventional Commit messages for staged changes; can install git hooks.
 */
const fs = require('fs'), path = require('path'), child = require('child_process');
exports.run = function(argv, ctx){
  const base = ctx.base;
  if (argv.includes('--hook') && argv.includes('install')) {
    const hookSrc = path.join(base,'hooks','prepare-commit-msg.example');
    const gitHookDir = '.git/hooks';
    try {
      fs.mkdirSync(gitHookDir,{recursive:true});
      fs.copyFileSync(hookSrc, path.join(gitHookDir,'prepare-commit-msg'));
      fs.chmodSync(path.join(gitHookDir,'prepare-commit-msg'), 0o755);
      console.log('Installed prepare-commit-msg hook (example).');
    } catch(e){
      console.error('Failed to install hook:', e.message);
    }
    return;
  }
  const commitMsg = `feat(auto): apply risn automated change\n\nGenerated by RISN AICM at ${new Date().toISOString()}`;
  fs.writeFileSync(path.join(base,'actions','aicm-commit.txt'), commitMsg);
  console.log('AICM commit message written to risn/actions/aicm-commit.txt');
};
