/**
 * risn marketing campaign --type email|social|shortvideo --product <slug> --audience <seg>
 */
const fs = require('fs'), path = require('path');
exports.run = function(argv, ctx){
  const base = ctx.base;
  const tIdx = argv.indexOf('--type'), pIdx = argv.indexOf('--product'), aIdx = argv.indexOf('--audience');
  const type = tIdx!==-1?argv[tIdx+1]:'email';
  const product = pIdx!==-1?argv[pIdx+1]:'sample';
  const audience = aIdx!==-1?argv[aIdx+1]:'all';
  const plan = {action:'marketing.campaign', type, product, audience, ts:new Date().toISOString()};
  fs.writeFileSync(path.join(base,'actions',`marketing-${product}-${Date.now()}.json`), JSON.stringify(plan,null,2));
  console.log('Marketing plan created. Assets will be generated by design pipeline and queued.');
};
